export const PROMPTS: string[] = [
  'a coffee mug',
  'a wooden chair',
  'a rocket',
  'a table',
  'a house',
  'a snowman',
  'a sailboat',
  'a hammer',
  'a ladder',
  'a traffic cone',
  'a birthday cake',
  'an arrow signpost',
  'a dumbbell',
  'a lamp',
  'a tent',
  'a mushroom',
  'a castle tower',
  'a bridge',
  'an airplane',
  'a bed',
  'a bench',
  'a windmill',
  'a lighthouse',
  'a tree',
  'a bottle',
  'a sword',
  'a key',
  'a crown',
  'a dog house',
  'a picture frame',
  'a bookshelf',
  'an umbrella',
  'a wine glass',
  'a staircase',
  'a fork',
  'a robot',
  'a duck',
  'a fish',
  'a car',
  'a piano',
]

export function randomPrompt(): string {
  return PROMPTS[Math.floor(Math.random() * PROMPTS.length)]
}
